name: euler-hs
version: 0.1.0.0
github: "janreggie/euler-hs"
license: MIT
author: "Jan Reggie Dela Cruz"
maintainer: ""
copyright: ""

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/janreggie/euler-hs#readme>

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative
  - split
  - containers
  - vector
  - array

library:
  source-dirs: src

executables:
  euler-hs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - euler-hs

tests:
  euler-hs-test:
    main: SolutionsTests.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - euler-hs
      - tasty
      - tasty-hunit
